### PR TITLE
Iterative hard thresholding

### PR DESCRIPTION
**Pull request by rossdwilliams**
added iht methods to plp

### CODE REVIEW

**Comment by jreps** [comment]
Great work Ross.  We will need to add IterativeHardThresholding as a dependency or use our function that checks whether people have it installed and offers to install it when they run it.  We are converting over to replace ffdf with Andromeda - so I might wait until then to pull this

**Comment by jreps** [comment]
Also - we need test coverage for this

**Comment by rossdwilliams** [comment]
Thanks! I have added tests for the set parameters, test that the function returns fewer than K covariates, roxygenised it and put ohdsi/IterativeHardThresholding in the remotes. Agree re andromeda

**Comment by jreps** [comment]
I need to make a few edits for Andromeda.  I need to update the develop branch with the latest master code and then maybe we can pull this into the develop and make any edits.

**Comment by jreps** [comment]
This looks pretty much complete - just needs updating for Andromeda and I think it is best to make the iterativeHardThreholding package dependency conditional (to keep the PLP package dependencies down).  Can you make this a pull request into either the development or iterativeHardThresholding branches and then I can make the minor edits :) ?

**Comment by rossdwilliams** [comment]
Fixed the merge errors and moved iht into the suggests (with the remote as ohdsi/iterativehardthreshold). I changed the pull request into development as well

Let me know if I need to do anything else

**Comment by jreps** [comment]
closing this to remove the development branch - this can be pulled into develop instead :)

**Pull request closed without merging**
