### PR TITLE
DeepLearning Using Torch

### PR DESCRIPTION
**Pull request by PRijnbeek**

### CODE REVIEW

**Comment by jreps** [comment]
This has a lot of files that are independent to the torch stuff and I don't want to risk edits that may break existing code.  Please only include: DESCRIPTION, NAMESPACE, R/CNNTorch.R, R/LRTorch.R, R/MLPTorch.R, R/PatientLevelPrediction.R, R/RNNTorch.R, inst/python/TorchUtils.py, inst/python/deepTorch.py, inst/python/python_predict.py and the manuals man/setCNNTorch.Rd, man/setLRTorch.Rd, man/setMLPTorch.Rd, man/setRNNTorch.Rd, man/toSparseTorchPython.Rd.  Plus maybe R/Formatting.R  if this is where you added the to sparse torch python?

**Comment by xypan1232** [comment]
Yes, here is the same as ensemble Training, I merged the latest master branch with my branch, then push changes back to my branch. So now I should create a new branch with only my changes,  @PRijnbeek , do you think how should we do? 

Yes, toSparseTorchPython in Formatting.R uses torch.sparse to save sparse data, which does not use tensorflow now.

**Comment by PRijnbeek** [comment]
@xypan1232 I am back at work tomorrow let me help you fixing this. You are doing a pull request to the deepLearningTorch branch at OHDSI here. If we accept this one a pull request to master from this feature branch will be clean and easier to handle by @jreps.

**Comment by xypan1232** [comment]
Hi @jreps, @PRijnbeek @lhjohn , I changed the base to master branch for this pull request, kept those files related to deeplearningTorch and removed some unnecessary changes with henrik's help, now the issues should be resolved.

**Pull request merged**
