### PR TITLE
Learning curve feature

### PR DESCRIPTION
**Pull request by lhjohn**
Functionality to create and plot learning curves objects.

### CODE REVIEW

**Comment by lhjohn** [comment]
I have merged the latest master into this feature branch.

The edits to the manuals were a result of lowercasing some of the R file names in the PLP package (e.g. PackagePlp.R to packagePlp.R), which I did not do. However, when I documented my functions using roxygen2, the other manuals also updated due to the new file name.

We have some file names starting with a capital letter and some starting with a lowercase letter. We could decide to use always a capital first letter, which would also revert all the changes to the manuals that this branch seems to introduce.

**Comment by lhjohn** [comment]
Some of the R file names have changed capitalization (e.g. PackagePlp.R became packagePlp.R). When I documented my functions using roxygen2 it also updated the manuals for all the functions that were renamed at an earlier point in time.

We could decide to let all R file names start with a capital letter, which should effectively revert the changes to the unrelated manuals in this feature branch.

**Comment by jreps** [comment]
I fixed the capitalization but the manuals still differ for a lot of files that shouldn't.  Can you remove the manual files that are not linked to the modifications? Also I fixed the existing tests so it will be cleaner to also remove any tests files that are not linked to the modifications.

**Comment by lhjohn** [comment]
Done. All remaining changes should belong to this feature.

**Comment by lhjohn** [comment]
Done. All remaining changes should belong to this feature.

**Pull request merged**
