### PR TITLE
Fix documentation

### LINKED ISSUE #364: Parametrized SQL in "Building patient-level predictive models"
In **Building patient-level predictive models**, the AfStrokeCohorts.sql script uses the parameter `@resultsDatabaseSchema` to call that object in R. However, the subsequent code does not use that object, but a different parameter: `@cohortsDatabaseSchema`.

```
library(SqlRender)
sql <- [readSql](https://ohdsi.github.io/SqlRender/reference/readSql.html)("AfStrokeCohorts.sql")
sql <- [renderSql](https://ohdsi.github.io/SqlRender/reference/renderSql.html)(sql,
cdmDatabaseSchema = cdmDatabaseSchema,
cohortsDatabaseSchema = cohortsDatabaseSchema,
post_time = 30,
pre_time = 365)$sql
sql <- [translateSql](https://ohdsi.github.io/SqlRender/reference/translateSql.html)(sql, targetDialect = connectionDetails$dbms)$sql
  
connection <- connect(connectionDetails)
executeSql(connection, sql)
```

This means the resulting SQL does not replace the parameter and thus throws an error.

### PR DESCRIPTION
**Pull request by egillax**
closes #364 and #363 

In addition this PR will:
-  Add website deployment to Github Actions so it's automatic with each new version
-  Add development website to test changes to the website/documentation before releasing on main
-  Update outdated pages as needed

### CODE REVIEW

**Comment by egillax** [comment]
So far I've:
- Updated function reference, exported function needed a group
- Made small adjustments to readme since now there is no python code in the package (only through reticulate)

**Comment by jreps** [comment]
Perfect - thanks for fixing the documents!

**Comment by egillax** [comment]
I haven't actually finished this PR,  so please don't merge it. That's why it's marked WIP (work in progress) and a draft PR. I've only done what's in the first comment.

**Comment by jreps** [comment]
FYI: I just updated the develop branch with the new shiny code (that now just uses ShinyAppBuilder) - it also required a few deps to have minimum version requirements (DatabaseConnector, ResultModelManager and OhdsiShinyModules).

**Comment by jreps** [comment]
Oh, also, would it be worth updating the shiny videos (in the readme and website) on running PLP?  run multiple pop v6: https://www.youtube.com/watch?v=7wUilx580PE , shiny v6: https://www.youtube.com/watch?v=BulmuH32y_Y and run pop: https://www.youtube.com/watch?v=7AraOsTynD4

**Comment by egillax** [comment]
Yes I'll add those videos. 

I've now updated this branch so the website build is automatic and there is a dev website:

https://ohdsi.github.io/PatientLevelPrediction/dev/index.html

That way the website is always up to date and we can review changes in the website before releasing.

It does require us to change the way we version in the DESCRIPTION file though. 

It requires the following process:
- Only update the version number when releasing to main
- The develop version is always the last released version with an added ".9000" at the end. 

I believe this is how most big R packages do it like arrow, torch and dplyr to name a few. 

What do you think about that @jreps  ?

**Comment by egillax** [comment]
@jreps , this is now ready for review. This is the initial PR with documentation fixes. To summarize

- Website build is automated using github actions
- A dev website will be built off the develop branch (currently it's from this branch but I will change it before merging)
- Updated the installation guide, the function reference, the video page and the feature engineering article
- Removed some unused stuff, some figures related to old deep learning tutorials, tex files from `inst/doc` which I don't believe belong there.
- I updated the minimum R version in DESCRIPTION, we depend on DatabaseConnector >= 6.0 which depends on R>=4.0
- Removed `docs/` directory, it's unnecessary. Now the website is deployed from a special branch `gh-pages`.

To see the dev website which is currently built from this PR:

https://ohdsi.github.io/PatientLevelPrediction/dev/

**Comment by jreps** [comment]
This looks great :)

**Pull request merged**
