### PR TITLE
Ensemble training

### PR DESCRIPTION
**Pull request by PRijnbeek**
- Added predict functionality
- Save and load functionality
- Documentation updated
- Use of validation set for training final layer in stacked model

### CODE REVIEW

**Comment by jreps** [comment]
This looks nice.  I've changed the default saving on runPlp (now you can say whether you want to save the plpData, plpResult, plots and summary.  This might impact the runEnsemble (e.g., you might want to have an option to save the data as if people are doing the ensemble to big datasets they probably want to turn off the saving data)

I also noticed the loadEnsemble uses the automatic saving of runPlp, it might be worth doing a saveEnsemble as well so they can save to a different location if they want?

**Comment by xypan1232** [comment]
Now I updated runEmsemble according to the new interface of Runplp in our local git, and will update to OHDSI soon.

**Comment by jreps** [comment]
The only files we need are the NAMESPACE, R/Ensemble.R, R/SaveLoadPlp.R and the ensemble manuals.  The other edits seem to just be reforming code or might make us revert to older code. I think if you only commit these files there will be no conflicts and I can pull this into master.

**Comment by xypan1232** [comment]
I just merged with the latest master branch, the conflict should be fixed now. Please help pull this into master. thanks

**Comment by jreps** [comment]
Please remove these files from the commit: R/RunPlp.R, R/Formatting.R, R/AdaBoost.R, man/createCohort.Rd, man/evaluateExistingModel.Rd, man/exportPlpResult.Rd, man/externalValidatePlp.Rd, man/packageResults.Rd, man/runPlp.Rd, man/setAdaBoost.Rd, man/setCovNN.Rd, man/standardOutput.Rd, man/submitResults.Rd. as these are independent to the ensemble code so are not needed and any modifications here might break existing code.

**Comment by xypan1232** [comment]
but these files should be the same as master branch? because i just merged the latest master branch with ensembleTraining branch.

**Comment by xypan1232** [comment]
Hi @jreps, @PRijnbeek @lhjohn , I removed some unnecessary changes with henrik's help, but runPlp.R, R/Formatting.R,  are needed. For Formatting.R, i added a change to make it can work on Linux to load python, and runPlp.R i added a new parameters for keeping some data as validation set to train stacked ensemble.

**Comment by jreps** [comment]
All looks great, I merged it.  Excited to try this!

**Pull request merged**
