### PR TITLE
Remove dependency on RSQLite

### PR DESCRIPTION
**Pull request by ablack3**
This PR removed the use of RSQLite to interact with Andromeda. I think I did this right but I have not tested these changes yet so it is possible that there is a typo or an error. For example I'm not sure that the anonymous function passed into batchApply can access the newCovariateData object.

### CODE REVIEW

**Comment by jreps** [comment]
Hi Adam,

I tested the code and the good news is that the batchApply code you write is a little bit quicker (5.2 mins vs 5.4 mins) than the current code.  However, it doesn't seem to be filtering correctly when I tried it.  I ran a test using 1 million patients data and a population of 200k, the current code returned ~20% of the covariates for the 1/5 population sample, but your code only returned 1.4% - so I think it is only keeping the single filter rather than combining. 

 I'm testing this revised code that can keep all the batches results:

start <- Sys.time()
newcovs <- Andromeda::batchApply(covariateData$covariates, function(tempData) {
  filtered <- tempData %>% dplyr::inner_join(population, by = 'rowId')
  return(filtered)
},
  progressBar = TRUE,
  batchSize = sizeN,
  safe = T
  )

newcovs <- dplyr::bind_rows(newcovs)

end <- Sys.time()

but this takes 10 mins and returns a data.frame rather than an Andromeda object (although we could do a loop around the original  newcovs to insert it into an Andromeda object).

I think we need a different function in Andromeda to let us update a global table inside a batch function

**Comment by jreps** [comment]
When safe = F the times goes to less than 5 mins (not sure when safe is needed)?

**Comment by jreps** [comment]
Actually, I think the issue is a typo: names(newCovariateData$covariates) should be names(newCovariateData) - that is why it is never getting updated.

**Comment by jreps** [comment]
can you make the edits:

1) remove line 58:   maxRows <- tally(covariateData$covariates, name = 'n') %>% collect() 
2) remove the $covariates on line 64

**Comment by ablack3** [comment]
Hi @jreps, 
I'm really sorry for the long delay. Thanks for your patience. I made the changes you suggested. I'm wondering why you would ever use `batchRestrict` instead of `limitCovariatesToPopulation`. `batchRestrict` pull all the data into R to do the row filtering and then loads it back into Andromeda.  `limitCovariatesToPopulation` loads the ids into Andromeda and does the filtering in the database which seem like it would be faster. Are you simply wanting a progress bar so you know how much time is left for this operation?

> I think we need a different function in Andromeda to let us update a global table inside a batch function

Maybe you can provide an example so I have a clear understanding. As far as I know the only way to do batch operations in the SQLite database is to split up the sql queries.

**Comment by jreps** [comment]
Hi Adam,

Thanks for making the edits.  The reason I added the batch restrict was due to sqlite scaling really badly.  I added indexes and tried to do an inner join on the covariate data (row_id) and population (row_id) to filter the covariates to just the patients on interest, but sqlite scales exponentially so with big data this simple join with indexes can take hours.  I tried writing different ways to do the filter with different SQL statements but all of them took age.  As the scaling was exponential, I figured splitting the task into smaller batches would give me linear scaling, which is much better (for example, if 10,000 patients takes 1 minute, then splitting 100,000 into 10x 10,000 takes 10 minutes, but without the batch splitting 100,000 patients was taking 30 minutes).

I did not test out changing the default sqlite configuration to a different max RAM - maybe that would help though?

It seems Egill may have found a solution to this issue by using Arrow.  The decrease in time he reported for PLP would be 99% due to improving the current sqlite data manipulation times (the rest of the code if using LASSO LR is super quick).

**Comment by ablack3** [comment]
This is helpful context. Yea I'm going to look at arrow and duckdb. Removing the SQLite dependency from other Hades packages will let me swap out the Andromeda backend. I'm surprised SQLite scales so badly for a join! If you have any performance tests you've written you'd be willing to share that would be helpful.

**Pull request merged**
