### PR TITLE
add VAE for dimension reduction

### PR DESCRIPTION
**Pull request by chandryou**
I added autoencoder (VAE) for dimension reduction to overcome the curse of dimension in CIReNN.
The output of 'buildVae' function is VAE and encoder.
So, if you want to reduce the dimension, you can use only encoder

It looks fine, but the total package doesn't work..
@jreps , Could you help me..?

Thank you in advance!

Signed-off-by: Seng Chan You <applegna@gmail.com>

### CODE REVIEW

**Comment by chandryou** [comment]
@jreps, I think I solved the problem, though the total process looks a little bit ugly
I need to update the setCIReNN.Rd for this update.

**Comment by chandryou** [comment]
@jreps  I updated the document, and checked that the total package worked in my environment. 
Thank you!

**Comment by xypan1232** [comment]
Hi Chan,

Do you apply VAE for 3D matrix, which dimension you try to reduce? I implemented VAE for 2D matrix consisting of |patient|X|feature|. How did you do it for temporal 3D data?

**Comment by chandryou** [comment]
Hi, @xypan1232 
Let 3D array 'X' consisting of 'Patient'(number of dimension = Dp) x 'Time span'(number of dimension = Dt) x 'Feature' (number of dimension = Df). Then 'X' has total of Dp x Dt x Df dimensions. 

To develop variational autoencoder, I converted 3D array into 2D array [DpxDt, Df] and build encoder with latent dimension (number of latent dimension = Dl)
After building encoder, I applied this encoder against 'Patient' dimension and 'Time' dimension, independently. (So if 'X' consists of 1000 patients with 10 Time span and 2000 features, autoencoder is applied to each time span of each patient to reduce number of features to 'Dl'. The original 3D array structure can be conserved, but the number of features would be reduced to latent dimensions. 

I'm sorry that my explanation is not enough.. If you have any question, please let me know!

**Pull request merged**
